app:
  port: 8100
#logs
log:
  configFile: config/log4js.json
#reverse proxy
reverseProxy:
  app:
    url: 'https://en.wikipedia.org/'
    proxyTimeout: 1000
  api:
    url: 'https://en.wikipedia.org'
    proxyTimeout: 1000
