app:
  port: 8100
#logs
log:
  configFile: config/log4js.json
#reverse proxy
reverseProxy:
  default:
    url: 'https://en.wikipedia.org/'
    proxyTimeout: 1000
  app:
    url: 'https://en.wikipedia.org/'
  api:
    url: 'http://ftp.riken.jp/Linux/'
