app:
  port: 8100
#logs
log:
  configFile: config/log4js.json
#reverse proxy
reverseProxy:
  app:
    url: http://localhost:8200
    proxyTimeout: 1000
  api:
    url: http://localhost:8200
    proxyTimeout: 1000
